/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.3
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupsV2GroupApplicationResolveState } from './groupsV2GroupApplicationResolveState';
import { UserUserInfoCard } from './userUserInfoCard';


export interface GroupsV2GroupMemberApplication { 
    groupId?: number;
    creationDate?: Date;
    resolveState?: GroupsV2GroupApplicationResolveState;
    resolveDate?: Date;
    resolvedByMembershipId?: number;
    requestMessage?: string;
    resolveMessage?: string;
    destinyUserInfo?: UserUserInfoCard;
    bungieNetUserInfo?: UserUserInfoCard;
}
