/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.3.3
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupsV2GroupPotentialMemberStatus } from './groupsV2GroupPotentialMemberStatus';
import { UserUserInfoCard } from './userUserInfoCard';


export interface GroupsV2GroupPotentialMember { 
    potentialStatus?: GroupsV2GroupPotentialMemberStatus;
    groupId?: number;
    destinyUserInfo?: UserUserInfoCard;
    bungieNetUserInfo?: UserUserInfoCard;
    joinDate?: Date;
}
