import { ApplicationDeveloper } from './ApplicationDeveloper';
import { ApplicationStatus } from './ApplicationStatus';
import { OAuthApplicationType } from './OAuthApplicationType';

export interface Application {
  applicationType?: OAuthApplicationType;
  /**
   * Unique ID assigned to the application
   */
  applicationId?: number;
  /**
   * Name of the application
   */
  name?: string;
  /**
   * URL used to pass the user's authorization code to the application
   */
  redirectUrl?: string;
  /**
   * Link to website for the application where a user can learn more about the app.
   */
  link?: string;
  /**
   * Permissions the application needs to work
   */
  scope?: number;
  /**
   * Value of the Origin header sent in requests generated by this application.
   */
  origin?: string;
  /**
   * Current status of the application.
   */
  status?: ApplicationStatus;
  /**
   * Date the application was first added to our database.
   */
  creationDate?: Date;
  /**
   * Date the application status last changed.
   */
  statusChanged?: Date;
  /**
   * Date the first time the application status entered the 'Public' status.
   */
  firstPublished?: Date;
  /**
   * List of team members who manage this application on Bungie.net. Will always consist of at least the application owner.
   */
  team?: Array<ApplicationDeveloper>;
}
